name: Deploy artifact

on:
  workflow_dispatch:

jobs:
  deploy-artifact:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p container
    - run: echo hello > container/artifact.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: container/artifact.txt
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          container/artifact.txt