# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: SImple up down

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: |
        mkdir build
        echo hello > build/hello.txt
#
#    - name: Package
#      shell: bash
#      run: |
#        zip -r hello.zip hello.txt

    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build/hello.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: "build-artifact"
          path: build/hello.txt

      - name: PWD
        run: pwd

      - name: Echo workspace
        run: echo ${{ github.workspace }}

      - name: Display structure of downloaded files
        run: ls -laR

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ inputs.version }}
          files: |
            build