# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: SImple up down

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: >
        echo hello > hello.txt

    - name: Package
      shell: bash
      run: |
        zip -r hello.zip hello.txt

    - uses: actions/upload-artifact@v4
      with:
        name: hello
        path: hello.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: "hello"

      - name: Display structure of downloaded files
        run: ls -R

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          files: |
            ${{ github.workspace }}/hello